// Mocks generated by Mockito 5.4.5 from annotations
// in top_up_app/test/domain/use_cases/get_beneficiary_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:top_up_app/core/error/server_failure.dart' as _i5;
import 'package:top_up_app/data/models/beneficiary_model.dart' as _i7;
import 'package:top_up_app/domain/entities/beneficiary.dart' as _i6;
import 'package:top_up_app/domain/repositories/beneficiary_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BeneficiaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeneficiaryRepository extends _i1.Mock
    implements _i3.BeneficiaryRepository {
  @override
  _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Beneficiary>>>
  getBeneficiaries() =>
      (super.noSuchMethod(
            Invocation.method(#getBeneficiaries, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.ServerFailure, List<_i6.Beneficiary>>
            >.value(
              _FakeEither_0<_i5.ServerFailure, List<_i6.Beneficiary>>(
                this,
                Invocation.method(#getBeneficiaries, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<
              _i2.Either<_i5.ServerFailure, List<_i6.Beneficiary>>
            >.value(
              _FakeEither_0<_i5.ServerFailure, List<_i6.Beneficiary>>(
                this,
                Invocation.method(#getBeneficiaries, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Beneficiary>>>);

  @override
  _i4.Future<_i2.Either<_i5.ServerFailure, _i6.Beneficiary>> addBeneficiary(
    _i7.BeneficiaryModel? beneficiary,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addBeneficiary, [beneficiary]),
            returnValue: _i4.Future<
              _i2.Either<_i5.ServerFailure, _i6.Beneficiary>
            >.value(
              _FakeEither_0<_i5.ServerFailure, _i6.Beneficiary>(
                this,
                Invocation.method(#addBeneficiary, [beneficiary]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<
              _i2.Either<_i5.ServerFailure, _i6.Beneficiary>
            >.value(
              _FakeEither_0<_i5.ServerFailure, _i6.Beneficiary>(
                this,
                Invocation.method(#addBeneficiary, [beneficiary]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.ServerFailure, _i6.Beneficiary>>);
}
